import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-affiliate-influencer-commission-reconciliation",
  "engine": "recovery",
  "title": "Affiliate & Influencer Commission Reconciliation",
  "shortTitle": "Affiliate and Influencer Commission Reconciliation",
  "tagline": "Reconcile partner commissions to valid attributed orders, returns, tiers, bonuses, and fraud controls.",
  "industry": "Performance Marketing Finance",
  "buyer": "Brands, networks, and ecommerce teams",
  "uiPort": 4731,
  "apiPort": 5731,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Affiliate & Influencer Commission Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments in one accountable workflow. Reconcile partner commissions to valid attributed orders, returns, tiers, bonuses, and fraud controls.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Affiliate & Influencer Commission Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("partner-agreement-library","AIC01","Partner agreement library","Execute partner agreement library using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed partner agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Partner agreement library Reference","text","AIC01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("tracking-link-code-registry","AIC02","Tracking link code registry","Execute tracking link code registry using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed tracking link code registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Tracking link code registry Reference","text","AIC02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("click-event-ingestion","AIC03","Click event ingestion","Execute click event ingestion using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed click event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Click event ingestion Reference","text","AIC03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("order-attribution","AIC04","Order attribution","Execute order attribution using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed order attribution decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Order attribution Reference","text","AIC04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("attribution-window-control","AIC05","Attribution window control","Execute attribution window control using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed attribution window control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Attribution window control Reference","text","AIC05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("coupon-poaching-detection","AIC06","Coupon poaching detection","Execute coupon poaching detection using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed coupon poaching detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Coupon poaching detection Reference","text","AIC06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("return-cancellation-reversal","AIC07","Return cancellation reversal","Execute return cancellation reversal using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed return cancellation reversal decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Return cancellation reversal Reference","text","AIC07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("commission-tier-calculation","AIC08","Commission tier calculation","Execute commission tier calculation using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed commission tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Commission tier calculation Reference","text","AIC08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("performance-bonus","AIC09","Performance bonus","Execute performance bonus using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed performance bonus decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Performance bonus Reference","text","AIC09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("self-referral-detection","AIC10","Self-referral detection","Execute self-referral detection using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed self-referral detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Self-referral detection Reference","text","AIC10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("fraud-traffic-scoring","AIC11","Fraud traffic scoring","Execute fraud traffic scoring using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed fraud traffic scoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Fraud traffic scoring Reference","text","AIC11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("partner-statement-audit","AIC12","Partner statement audit","Execute partner statement audit using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed partner statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Partner statement audit Reference","text","AIC12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("dispute-workflow","AIC13","Dispute workflow","Execute dispute workflow using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Dispute workflow Reference","text","AIC13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("payment-correction","AIC14","Payment correction","Execute payment correction using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed payment correction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Payment correction Reference","text","AIC14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]}),
feature("partner-campaign-analytics","AIC15","Partner campaign analytics","Execute partner campaign analytics using partner agreements, links, codes, clicks, orders, returns, attribution windows, commission tiers, bonuses, fraud signals, invoices, and payments.","Produce a governed partner campaign analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Campaign","text","Partner / Campaign · Standard Case"],["caseReference","Partner campaign analytics Reference","text","AIC15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1717500],["supportedAmount","Evidence-Supported Amount","currency",1442700],["domainDriver","Partner Type","select","Affiliate publisher",["Affiliate publisher","Influencer","Ambassador"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Partner agreement library case","Tracking link code registry case","Click event ingestion case","Order attribution case","Attribution window control case"]})
]);
